#-*- coding: utf-8 -*-
menu=   [
            {
                "name":"Agendas",
                "url":"/agendas",
                "method":"Post",
                "value":"menuAgendas"
            },
            {
                "name":"Solicitudes",
                "url":"/solicitudes",
                "method":"Post",
                "value":"menuSolicitudes"
            },
            {
                "name":"Contactados",
                "url":"/contactados",
                "method":"Post",
                "value":"menuContactados"
            },
            {
                "name":"Entregados a Riesgos",
                "url":"/entregadosariesgos",
                "method":"Post",
                "value":"menuEntregadosaRiesgos"
            },
            {
                "name":"Mesa de Analisis",
                "url":"/mesadeanalisis",
                "method":"Post",
                "value":"menuMesaDeAnalisis"
            },
            {
                "name":"Revision Documental",
                "url":"/revisionDocumental",
                "method":"Post",
                "value":"menuRevisionDocumental"
            },
            {
                "name":"Consultas Buro y QQ",
                "url":"/consultasBuroyQQ",
                "method":"Post",
                "value":"menuConsultasBuroyQQ"
            },
            {
                "name":"Pre Analsis",
                "url":"/preAnalisis",
                "method":"Post",
                "value":"menuPreAnalisis"
            },
            {
                "name":"Analisis de Creditos",
                "url":"/analisisCreditos",
                "method":"Post",
                "value":"menuAnalisisCreditos"
            },
            {
                "name":"Solicitar VoBo's",
                "url":"/solicitarvobos",
                "method":"Post",
                "value":"menuSolicitarVoBos"
            },
             {
                "name":"Autorizacion Riesgos",
                "url":"/autorizacionriesgos",
                "method":"Post",
                "value":"menuAutorizacionRiesgos"
            },
            {
                "name":"Autorizacion DG",
                "url":"/autorizaciondg",
                "method":"Post",
                "value":"menuAutorizacionDG"
            },
            {
                "name":"Imprimir Contrato",
                "url":"/imprimircontrato",
                "method":"Post",
                "value":"menuImprimirContrato"
            },
            {
                "name":"Firmar Contrato",
                "url":"/firmarcontrato",
                "method":"Post",
                "value":"menuFirmarContrato"
            },
            {
                "name":"Por Fondear",
                "url":"/porfondear",
                "method":"Post",
                "value":"menuPorFondear"
            },
            {
                "name":"Transferencias",
                "url":"/transferencias",
                "method":"Post",
                "value":"menuTransferencias"
            },
            {
                "name":"Fondeados",
                "url":"/fondeados",
                "method":"Post",
                "value":"menuFondeados"
            },
            {
                "name":"Rechazados",
                "url":"/rechazados",
                "method":"Post",
                "value":"menuRechazados"
            },
            {
                "name":"Control de Expedientes",
                "url":"/controlexpedientes",
                "method":"Post",
                "value":"menuControlExpedientes"
            },
            {
                "name":"Cobranza",
                "url":"/cobranza",
                "method":"Post",
                "value":"menuCobranza"
            },
            {
                "name":"Historico",
                "url":"/historico",
                "method":"Post",
                "value":"menuHistorico"
            },
            {
                "name":"Simulador",
                "url":"/simulador",
                "method":"Post",
                "value":"menuSimulador"
            },
            {
                "name":"Seguimiento Diario",
                "url":"/seguimientodiario",
                "method":"Post",
                "value":"seguimientoDiario"
            },
            {
                "name":"PipeLine",
                "url":"/pipeline",
                "method":"Post",
                "value":"menuPipeLine"
            },
            {
                "name":"ScoreCard",
                "url":"/scorecard",
                "method":"Post",
                "value":"menuScoreCard"
            },
            {
                "name":"Colocacion",
                "url":"/colocacion",
                "method":"Post",
                "value":"menuColocacion"
            },
            {
                "name":"Cumplimiento",
                "url":"/cumplimiento",
                "method":"Post",
                "value":"menuCumplimiento"
            },
            {
                "name":"Cosechas",
                "url":"/cosechas",
                "method":"Post",
                "value":"menuCosechas"
            },
            {
                "name":"Op Interna Preocupante",
                "url":"/reporteOIP",
                "method":"Post",
                "value":"menuOIP"
            },
            {
                "name":"Reporte de Ventas",
                "url":"/reporteVentas",
                "method":"Post",
                "value":"menuReporteVentas"
            },
            {
                "name":"CLABES",
                "url":"/clabes",
                "method":"Post",
                "value":"menuClabes"
            },
            {
                "name":"Perfil",
                "url":"/perfil",
                "method":"Post",
                "value":"menuPerfil"
            },
            {
                "name":"Usuarios",
                "url":"/usuarios",
                "method":"Post",
                "value":"menuUsuarios"
            },
            {
                "name":"ACL",
                "url":"/acl",
                "method":"Post",
                "value":"menuACL"
            },
            {
                "name":"Empresas",
                "url":"/empresas",
                "method":"Post",
                "value":"menuEmpresas"
            },
            {
                "name":"Pagadoras",
                "url":"/pagadoras",
                "method":"Post",
                "value":"menuPagadoras"
            },
            {
                "name":"Asignaciones",
                "url":"/asignaciones",
                "method":"Post",
                "value":"menuAsignaciones"
            },
            {
                "name":"Visitas",
                "url":"/visitas",
                "method":"Post",
                "value":"menuVisitas"
            },
            {
                "name":"Logs",
                "url":"/logs",
                "method":"Post",
                "value":"menuLogs"
            },
            {
                "name":"BackUps",
                "url":"/backups",
                "method":"Post",
                "value":"menuBackUps"
            },
            {
                "name":"Sesiones Activas",
                "url":"/sesiones",
                "method":"Post",
                "value":"menuSesiones"
            },
            {
                "name":"Reporte de Texto",
                "url":"/reporteDeTexto",
                "method":"Post",
                "value":"menuReporteTexto"
            },
            {
                "name":"Salir",
                "url":"/logout",
                "method":"Get",
                "value":"menuSalir"
            }
        ]

login=   [
            {
                "name":"Ingresar",
                "url":"/",
                "method":"Get",
                "value":"menuIngresar"
            }
        ]

